### ISSUE TITLE
Invalid Comment linebreak

### ISSUE THREAD

**Issue by IIIuminator** [jmfayard/buildSrcVersions#32]
When running `buildSrcVersions` I got this linebreak
```Kotlin
const val community_material_typeface: String = "3.1.0-rc02" // exceed the version found:
            2.7.94.1
```
resulting in invalid code. Tired it multiple times (also with Android Studio closed, in case its some auto-format issue) and it happens every time.

**Comment by jmfayard** [comment]
Thanks. Same problem than in https://github.com/square/kotlinpoet/issues/561

That message "exeed the version found" is useless anyway. 

If you keep `"3.1.0-rc02"` it's probably because the version does exist, but either not in the repository by default or we rejected the version because it's  a RC02 version. 
https://github.com/jmfayard/buildSrcVersions/issues/29

I removed it in version 3.0.2 of the plugin that should be now available
