### ISSUE TITLE
Improve dependency update workflow

### ISSUE THREAD

**Issue by eikemeier** [jmfayard/buildSrcVersions#37]
First, thanks for this wonderful plugin.

I agree that version updates should be confirmed or rejected by the developer. I was using [gradle-libraries-plugin](https://github.com/fkorotkov/gradle-libraries-plugin), and since my source is in git I was reviewing every change `dependencies.json` in my favorite git tool after doing `updateLibraries`.

The point is that this plugin should offer an option the actually **change** the versions, since I have to review the changes anyway. Having a “remove comments manually” step adds nothing and makes things more complicated.

Also, for [creating a `.gitignore` file](https://github.com/jmfayard/buildSrcVersions/issues/3): Not everyone is using git, so this plugin should make no assumptions, and I need to manage my own `.gitignore` file anyway - this shouldn't be there.

Both are topics with what this plugin should be concerned and what are actually tasks that are necessary, but not the responsibility of this plugin.

Thanks
Oliver

**Comment by jmfayard** [comment]
Hello, regarding `.gitignore`, I like to think in terms of use cases.

- the most common use case is that the developer does use git. She uses the plugin which generates a couple of files. Then she commit. Later she builds the projects again and commit. She didn't realize that because Gradle compiled the new `buildSrc` module, a bunch of files were created in `buildSrc/buidld` and feels a bit stupid by this simple mistake. I don't like people feeling stupid so I want to do the right thing by default. 
- Now if someone use no version control, having an additional `.gitignore`  file does not hurt, so I'm fine with it.
- If someone uses git and modify the `.gitignore` file, this is still fine because I'm not touching the file once it's created.
- If someone uses another VCS, let say mercurial. He can use the `.gitignroe` file as a template of what needs to be ignored. He will probably delete the `.gitignore` file once he is done. Here I was not doing the right thing because I re-created the file when it was not present. In the next version, I will not do that anymore. Thanks for the bug report @eikemeier

**Comment by jmfayard** [comment]
> I agree that version updates should be confirmed or rejected by the developer. I was using gradle-libraries-plugin, and since my source is in git I was reviewing every change dependencies.json in my favorite git tool after doing updateLibraries.
> The point is that this plugin should offer an option the actually change the versions, since I have to review the changes anyway. 

So it's not about having an interactive tool that asks for each version whether you want to apply the update, but for an option to update all versions? 
Your workflow is interesting (trust the tool, then review all changes with a diff tool) but I am not sure this is a path I want to go.

**Comment by jmfayard** [comment]
I have no plans to implement an interactive tools. Closing this for now
