### ISSUE TITLE
why this creates a settings.gradle file inside buildSrc folder?

### ISSUE THREAD

**Issue by desanik** [jmfayard/buildSrcVersions#42]
why this plugin creates a settings.gradle file inside buildSrc folder?

**Comment by jmfayard** [comment]
Hello @desanik 
Gradle explains here why you should always have a settings file at the root of your project
https://docs.gradle.org/current/userguide/organizing_gradle_projects.html#always_define_a_settings_file

From a conversation with some Gradle developers, I got the impression that it was a good thing to add one in the buildSrc as well, but I am not sure I understood it correctly.

**Comment by desanik** [comment]
By you own rule : **at the root of your project** is not inside _buildSrc_. Look at the proposed structure for buildSrc : <https://docs.gradle.org/current/userguide/organizing_gradle_projects.html#sec:build_sources>
They don't add a _setting.gradle_ file inside _buildSrc_. You can find the structure a little down the page from your own link.
That empty settings file does nothing at best, but if you fill it with something (Some people will try, I did;) ), the IDE gets confused (tries to load buildSrc into the project compile classpath), so this an unnecessary generated source of IDE bugs. Also, I really think adding an empty file to the git repo is kind of a "this code smells" situation. I modified you task to delete the file after creation, i hope you reconsider so I don't have to hack your marvellous tool.

**Comment by cjbrooks12** [comment]
The `buildSrc` is effectively an "included Gradle build", and can itself have subprojects, etc. and should be structured just like a normal Gradle project.

That said, generating the boilerplate for `buildSrc` really should not be a concern for this plugin. It should create the `Libs.kt` and `Versions.kt` files, and that's it. Maybe log a warning if the boilerplate files do not exist so the user can create them, but don't generate them automatically. I just ran this in a project that already has `buildSrc` set up, and had to go delete the extra files generated because I already had them. I have the groovy files I need, and each time I run this to update versions I'm going to have to delete the Kotlin files generated from this plugin, which is really annoying.

**Comment by jmfayard** [comment]
Sorry for the late reply @cjbrooks12 @desanik 
I have seen sick and gave up on this project for a while. 
I have published version 0.4.0 of this pluginn that 1) do not create a buildSrc/settings.gradle.kts file anymore 2) does not create buildSrc/build.gradle.kts if buildSrc/build.gradle is already there
