### ISSUE TITLE
[suggestion] Generate `Projects.kt` file with all subprojects

### ISSUE THREAD

**Issue by cjbrooks12** [jmfayard/buildSrcVersions#61]
I love using this plugin to manage external dependencies, but when setting up intra-project dependencies amongst subprojects of a single repo, I have to resort to using Stringly-typed values again with `implementation(project(":..."))`. It would be really nice if this plugin could generate a solution for this problem as well.

My proposal is to generate a 3rd file, `Projects.kt`, and in it generate functions for referencing each Gradle subproject as a dependency. It would be especially nice if this file used nested `object`s to make it easier to reference.

I just hand-wrote this kind of file for my own project, and it seems to be working really well. Makes setting up and referencing my subprojects/groups of subprojects much easier, and it would be awesome to have this file generated automatically. The links below show sample usage of what this could look like, but I just threw this together and am open to any suggestions for better structure.

- [Projects.kt](https://github.com/JavaEden/Orchid/blob/dev/buildSrc/src/main/kotlin/Projects.kt)
- [Auto-register subprojects in `settings.gradle`](https://github.com/JavaEden/Orchid/blob/dev/settings.gradle.kts#L13-L18)
- [Setup dependency on single project](https://github.com/JavaEden/Orchid/blob/dev/bundles/OrchidDocs/build.gradle.kts#L2)
- [Setup dependency on an entire group of projects](https://github.com/JavaEden/Orchid/blob/dev/bundles/OrchidLanguagePack/build.gradle.kts#L3)

**Comment by jmfayard** [comment]
Sounds good looking at it

**Comment by jmfayard** [comment]
@cjbrooks12 I refactored it to use an Enum and extension functions and it makes me think that it could be generalized quite easily and would be useful!

https://github.com/JavaEden/Orchid/pull/306

(You don't have to merge it, just an example). 

I won't work on it though because I'm not using complex Gradle modules right now, so I don't know the use cases really well. 

But I would be more than happy to provide support if anyone wants to try out implementing this feature!

**Comment by cjbrooks12** [comment]
Yeah, I like that approach better, passing enums/lists of enums to top-level extension functions. And I'd be happy to work on implementing this, it shouldn't be too difficult.

**Comment by jmfayard** [comment]
Cool! Wait a bit that I'm done with issue #55 which includes quite a large
refactoring. I will ping you

Le mer. 4 sept. 2019 à 16:54, Casey Brooks <notifications@github.com> a
écrit :

**Comment by jmfayard** [comment]
@cjbrooks12 I'm done with #55, you can start by forking from master. 

When I refactored your example, I use the term `Module` instead of `Project`, but it was mostly for not conflicting with what you did. Feel free to use whatever term is better. 

On the other hand, I think that new features like this should be an opt-in. See this ticket about adding a plugin configuration option
https://github.com/jmfayard/buildSrcVersions/issues/53

To contribute you should open the composite module in IntelliJ
See this issue https://github.com/jmfayard/buildSrcVersions/issues/31

To develop, I usually rely on the samples, but for your particular feature that won't help you much. It's best to test it locally with your project. 

So edit `JavaEden/Orchid` like this:

```kotlin
// settings.gradle.kts
pluginManagement {
    repositories {
        val localGradleRepo = "FULL_PATH_TO/buildSrcVersions/plugin/build/repository"
        if (File(localGradleRepo).exists()) maven { setUrl(localGradleRepo) }
        gradlePluginPortal()
   }
}

// build.gradle.kts
plugins {
  id("de.fayard.buildSrcVersions").version("0.5.0")
}
```

Now each time you do a change
- run the task `:publishLocally` from `buildSrcVersions-composite`
- run the task `:buildSrcVersions`  from `JavaEden/Orchid`

**Comment by jmfayard** [comment]
I learned in #60 that `settinhgs.gradle.kts` would not be able to depend from the `buildSrc` in a future version of Gradle.

**Comment by jmfayard** [comment]
This is still a good tip for people busing the `buildSrc` 

But this project will now focus on `:refreshVersions`

See Long term plan: focus on refreshVersions · Issue #104 ·
